path: C:/Users/KSHIT/OneDrive/Desktop/FruitFreshnessDetection/data/YoloDataset
train: train/images
val: valid/images

names:
  0: Apple
  1: Banana
  2: Grape
  3: Orange
  4: Pineapple
  5: Watermelon